# MySQL. Ensure the MySQL gem is defined in your Gemfile:
#   gem 'mysql2'
#
# Configure using the following format:
# log database configurations
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("MYSQL_HOST") { '127.0.0.1' } %>
  database: <%= ENV.fetch("MYSQL_DATABASE") { 'chat_system' } %>
  port: <%= ENV.fetch("MYSQL_PORT") { 3306 } %>

development:
  <<: *default


test:
  <<: *default

production:
  <<: *default

