# MySQL. Ensure the MySQL gem is defined in your Gemfile:
#   gem 'mysql2'
#
# Configure using the following format:
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>
  username: root
  password: password
  host: 127.0.0.1
  database: chat_instabug
  port: 3306

development:
  <<: *default


test:
  <<: *default

production:
  <<: *default

