:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 5 } %>
:queues:
  - default
  - create_chat_queue

:logging:
  :enabled: true
  :level: info
  :format: default

:verbose: false

:scheduler:
  :schedule:
    update_counters_job:
      cron: "*/1 * * * *"
      class: "UpdateCountersJob"
      queue: "default"

:pidfile: tmp/pids/sidekiq.pid

:redis:
  :url: <%= ENV.fetch("SIDEKIQ_REDIS_URL") { "redis://localhost:6379/1" } %>
  :namespace: "chat_app_sidekiq"
